export const GAME_CONFIG = {
	PACMAN_BASE_SPEED: 10,
	PACMAN_RESPAWN_DELAY_SEC: 1.5,

	GHOST_NORMAL_SPEED: 8,
	GHOST_EATEN_SPEED: 20,
	GHOST_EXIT_DELAY: 2, //never zero

	POWER_PELLET_DURATION: 10,
	GHOST_FLASH_DURATION: 3,
	GHOST_FLASH_INTERVAL: 0.2,
} as const;

export const HUD_CONFIG = {
	MAIN_MENU_MOVE_CD: 100,
} as const;