/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GameExperience: typeof import('./src/components/GameExperience.vue')['default']
    GameHUD: typeof import('./src/components/GameHUD.vue')['default']
    IMdiHeart: typeof import('~icons/mdi/heart')['default']
    IPixelarticonsHeart: typeof import('~icons/pixelarticons/heart')['default']
    IPixelarticonsPause: typeof import('~icons/pixelarticons/pause')['default']
  }
}
